### ISSUE TITLE
Compatibility issue with optifine

### ISSUE THREAD

**Issue by krzysztof9989** [YuRaNnNzZZ/More-Red-CCT-Compat#2]
MC 1.20.1
Forge 47.2.0
CC:Tweaked 106.1 - 109.6
MoreRed 4.0.0.4
MoreRed CCT Compat 1.0.0
Optifine 1.20.1 HD U I6

JVM arguments:
-Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

PC specs
R3 3100
GTX 1060 6GB
24GB RAM

There's a weird compatibility issue with optifine
rs.getBundledInput() works fine but rs.setBundledOutput() doesn't, no redstone signal is produced
When I unload optifine it works as expected.

Also here's debug.log
[debug.txt](https://github.com/YuRaNnNzZZ/More-Red-CCT-Compat/files/14336552/debug.txt)

**Comment by YuRaNnNzZZ** [comment]
Current CC:T version already features native More Red bundled cables support, which is also broken with OptiFine. I believe OptiFine is the problem.
