### ISSUE TITLE
1.21 Neoforge

### ISSUE THREAD

**Issue by Karotte128** [YuRaNnNzZZ/More-Red-CCT-Compat#3]
Please port to 1.21 Neoforge.

**Comment by YuRaNnNzZZ** [comment]
Given how native compatibility was added in 1.20.1 version of CC:T, I assume 1.21 will get it as well.
(plus I'm not willing to bother with NF and with both mods missing from MCForge, it is unlikely a version for 1.21 will come from me)

**Comment by YuRaNnNzZZ** [comment]
eb394da12f33da08a0a04cca3b1f2f5468b29ce0

waiting for CF approval (not on modrinth until more red 1.21 is uploaded there as well)
